{% set name = "autoray" %}
{% set version = "0.6.9" %}
{% set sha256 = "9f41759f6a286bc280c4f6aece436da1c87ce75eb00efe7dc7319860c43654fa" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - setuptools-scm >=7
    - pip
  run:
    - python >=3.8

test:
  imports:
    - autoray
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://autoray.readthedocs.io
  summary: Abstract your array operations.
  dev_url: https://github.com/jcmgray/autoray/
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache

extra:
  recipe-maintainers:
    - jcmgray
