{% set name = "autoray" %}
{% set version = "0.7.1" %}
{% set sha256 = "e5af6c62ba7c3be8a36b2ab19e344c715f3478d39a0e47755aad365572bc90f8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - setuptools-scm >=7
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - autoray
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://autoray.readthedocs.io
  summary: Abstract your array operations.
  dev_url: https://github.com/jcmgray/autoray/
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache

extra:
  recipe-maintainers:
    - jcmgray
