{% set name = "autoray" %}
{% set version = "0.8.4" %}
{% set sha256 = "b4ce7066334279b216431a260bb5b5b84d87815e3295020a76d8701e43dc3432" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - autoray
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://autoray.readthedocs.io
  summary: Abstract your array operations.
  dev_url: https://github.com/jcmgray/autoray/
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache

extra:
  recipe-maintainers:
    - jcmgray
