{% set name = "autoray" %}
{% set version = "0.5.0" %}
{% set sha256 = "c49102fb7fa09fc1d17e7d2eeb0ffb6a6f5c9ff45f104e88c5b062fc8008e1fd" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - numpy
    - python >=3.5

test:
  imports:
    - autoray
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jcmgray/autoray/
  summary: Write backend agnostic numeric code compatible with any numpy-ish array library.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache

extra:
  recipe-maintainers:
    - jcmgray
