{% set name = "autoray" %}
{% set version = "0.7.0" %}
{% set sha256 = "7829d21258512f87e02f23ce74ae5759af4ce8998069d2cce53468f1d701a219" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - setuptools-scm >=7
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - autoray
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://autoray.readthedocs.io
  summary: Abstract your array operations.
  dev_url: https://github.com/jcmgray/autoray/
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache

extra:
  recipe-maintainers:
    - jcmgray
